"""
Model 1: Student Development Clustering (Section 21 of the brief).

K-Means groups students into development "profiles". Cluster IDs are unsupervised
and unordered — labels are assigned post-hoc by inspecting each cluster's
strongest average features, exactly as the brief instructs: "The labels can be
generated by interpreting cluster characteristics, rather than treating them as
fixed truths."
"""
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
import numpy as np

PROFILE_SIGNATURES = {
    'Academic Focused': ['attendance_rate', 'assignment_completion', 'academic_discipline'],
    'Technical Innovator': ['technical_engagement', 'certifications', 'hackathons'],
    'Leadership Oriented': ['leadership_exposure', 'leadership_roles', 'team_projects'],
    'Extracurricular Focused': ['extracurricular_balance', 'sports_participation', 'event_participation'],
    'Balanced Performer': [],  # fallback when no single signature dominates
}


def run_clustering(X, feature_names, n_clusters=5, random_state=42):
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    model = KMeans(n_clusters=n_clusters, random_state=random_state, n_init=10)
    labels = model.fit_predict(X_scaled)

    sil_score = silhouette_score(X_scaled, labels) if len(set(labels)) > 1 else None

    # Interpret each cluster's centroid (in original feature space) to assign a
    # human-readable profile name.
    centroids_scaled = model.cluster_centers_
    centroids = scaler.inverse_transform(centroids_scaled)
    profile_names = _assign_profile_names(centroids, feature_names)

    return {
        'labels': labels.tolist(),
        'silhouette_score': round(float(sil_score), 4) if sil_score is not None else None,
        'cluster_profiles': profile_names,
        'centroids': centroids.tolist(),
        'feature_names': feature_names
    }


def _assign_profile_names(centroids, feature_names):
    """For each cluster centroid, find which signature's features are most
    elevated relative to the other clusters, and assign that profile name."""
    names = []
    used = set()
    feature_idx = {f: i for i, f in enumerate(feature_names)}

    # z-score each feature column across clusters so "elevated" is relative, not absolute
    centroids_arr = np.array(centroids)
    col_mean = centroids_arr.mean(axis=0)
    col_std = centroids_arr.std(axis=0) + 1e-6
    z = (centroids_arr - col_mean) / col_std

    for i in range(len(centroids)):
        best_profile, best_score = 'Balanced Performer', -np.inf
        for profile, sig_features in PROFILE_SIGNATURES.items():
            if not sig_features or profile in used and len(used) < len(PROFILE_SIGNATURES):
                continue
            idxs = [feature_idx[f] for f in sig_features if f in feature_idx]
            if not idxs:
                continue
            score = z[i, idxs].mean()
            if score > best_score:
                best_score, best_profile = score, profile
        names.append(best_profile)
        used.add(best_profile)
    return names
